"""add_pillar_scores_to_submissions

Revision ID: 6107d3ed6920
Revises: 
Create Date: 2026-05-05 16:57:34.503379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6107d3ed6920'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('pillar_scores', sa.JSON(), nullable=True))
    op.add_column('submissions', sa.Column('executive_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'executive_summary')
    op.drop_column('submissions', 'pillar_scores')
    # ### end Alembic commands ###
